FROM centos

RUN yum update -y
RUN yum install -y wget vim tmux curl git bzip2 epel-release && \
    yum install -y python-pip R unixODBC unixODBC-devel libxml2-devel libcurl-devel openssl-devel sssd-tools initscripts krb5-workstation krb5-libs krb5-auth-dialog enchant python-devel
